### ISSUE TITLE
Shell Quick-Execute

### ISSUE THREAD

**Issue by Feliix42** [kiliankoe/cage#1]
This tool definitely needs a super-secure, fast to type way to execute it, like the rustup installation command:
```
curl https://sh.rustup.rs -sSf | sh
```

_Of course, only for serious and non-trolling use cases._

**Comment by kiliankoe** [comment]
😍

**Comment by kiliankoe** [comment]
Not quite using this tool, but here you go 🙈😄

```
curl -sL git.io/cage | sh
```
